{{- $labels := include "multi-gatekeeper.labels" . -}}
{{- $selectorLabels := include "multi-gatekeeper.selectorLabels" . -}}

{{- $values := .Values -}}

{{- range .Values.proxies }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "multi-gatekeeper.name" . }}
  namespace: {{ .namespace }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: {{ $values.service.type }}
  ports:
    - port: {{ $values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- $selectorLabels | nindent 4 }}
    app.kubernetes.io/name: {{ include "multi-gatekeeper.name" . }}
{{- end }}